---
defaulted: false
nginx_http_port: 80
nginx_https_port: 443
php_fpm_port: 9000
nginx_conf_template: "nginx.conf.j2"
nginx_webroot: "/var/www/html"
nginx_user: "ec2-user"
nginx_error_log: "/var/log/nginx/error.log warn"
nginx_pidfile: "/var/run/nginx.pid"
nginx_client_max_body_size: "50M"
nginx_access_log: "/var/log/nginx/access.log main"
#nginx_access_log: "off"
nginx_sendfile: "on"
nginx_tcp_nopush: "on"
nginx_tcp_nodelay: "on"
nginx_keepalive_timeout: "2"
nginx_keepalive_requests: "100000"
nginx_server_tokens: "off"
nginx_worker_processes: "auto"
nginx_worker_rlimit_nofile: 100000
nginx_worker_connections: "8192"
nginx_multi_accept: "on"
nginx_mime_file_path: /etc/nginx/mime.types
server_name: "{{ ansible_hostname | default('localhost') }}"
nginx_log_format: |-
  '$remote_addr - $remote_user [$time_local] "$request" '
  '$status $body_bytes_sent "$http_referer" '
  '"$http_user_agent" "$http_x_forwarded_for"'
nginx_conf_path: "/etc/nginx/conf.d"
nginx_conf_file_path: "/etc/nginx/nginx.conf"
secure: true
cgi: fastcgi
